In [ ]:
!pip install pyspark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.4.1-py2.py3-none-any.whl size=311285397 sha256=2954ec8aa2e3146c60a8ed011e34bf96eefbb6fbc7446c62dadda6687e21b935
  Stored in directory: /root/.cache/pip/wheels/0d/77/a3/ff2f74cc9ab41f8f594dabf0579c2a7c6de920d584206e0834
Successfully built pyspark


In [ ]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("alpha").getOrCreate()

In [ ]:
spark

In [ ]:
data = spark.sparkContext.textFile("/content/sample_data/california_housing_test.csv")
# here the textFile is transformation, So it only create a lineage (ADG)
# the actual data will not be loaded

In [ ]:
data.take(10)
# the above will print the first 10 lines
# take is an action

['"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"',
 '-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000',
 '-118.300000,34.260000,43.000000,1510.000000,310.000000,809.000000,277.000000,3.599000,176500.000000',
 '-117.810000,33.780000,27.000000,3589.000000,507.000000,1484.000000,495.000000,5.793400,270500.000000',
 '-118.360000,33.820000,28.000000,67.000000,15.000000,49.000000,11.000000,6.135900,330000.000000',
 '-119.670000,36.330000,19.000000,1241.000000,244.000000,850.000000,237.000000,2.937500,81700.000000',
 '-119.560000,36.510000,37.000000,1018.000000,213.000000,663.000000,204.000000,1.663500,67000.000000',
 '-121.430000,38.630000,43.000000,1009.000000,225.000000,604.000000,218.000000,1.664100,67000.000000',
 '-120.650000,35.480000,19.000000,2310.000000,471.000000,1341.000000,441.000000,3.225000,166900.000000',
 '-122.840000,38.400000,15.0000

In [ ]:
print(data)

/content/sample_data/california_housing_test.csv MapPartitionsRDD[21] at textFile at NativeMethodAccessorImpl.java:0


In [ ]:
y = spark.sparkContext.parallelize(["hea", "no idea what's happening here"])

In [ ]:
print(y)

ParallelCollectionRDD[3] at readRDDFromFile at PythonRDD.scala:287


In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris_data = load_iris()

In [ ]:
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
iris_data_sp = spark.sparkContext.parallelize(iris_data.data)

In [ ]:
iris_data_sp

ParallelCollectionRDD[24] at readRDDFromFile at PythonRDD.scala:287

In [ ]:
## Printing the  lines of data

In [ ]:
iris_data_sp.first()

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
iris_data_sp.collect()

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.

In [ ]:

iris_data_sp.take(20)

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3])]

In [ ]:
# setting the name
# default one
print(iris_data_sp.name())
# setting the name
iris_data_sp.setName("rdd_delta0")
print("after changing the name:", iris_data_sp.name())

None
after changing the name: rdd_delta0


In [ ]:
# saving the file
# iris_data_sp.saveAsTextFile("iris_sp.csv")

In [ ]:
iris_data_sp

rdd_delta0 ParallelCollectionRDD[24] at readRDDFromFile at PythonRDD.scala:287

In [ ]:
print(iris_data_sp.collect())

[array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2]), array([4.6, 3.1, 1.5, 0.2]), array([5. , 3.6, 1.4, 0.2]), array([5.4, 3.9, 1.7, 0.4]), array([4.6, 3.4, 1.4, 0.3]), array([5. , 3.4, 1.5, 0.2]), array([4.4, 2.9, 1.4, 0.2]), array([4.9, 3.1, 1.5, 0.1]), array([5.4, 3.7, 1.5, 0.2]), array([4.8, 3.4, 1.6, 0.2]), array([4.8, 3. , 1.4, 0.1]), array([4.3, 3. , 1.1, 0.1]), array([5.8, 4. , 1.2, 0.2]), array([5.7, 4.4, 1.5, 0.4]), array([5.4, 3.9, 1.3, 0.4]), array([5.1, 3.5, 1.4, 0.3]), array([5.7, 3.8, 1.7, 0.3]), array([5.1, 3.8, 1.5, 0.3]), array([5.4, 3.4, 1.7, 0.2]), array([5.1, 3.7, 1.5, 0.4]), array([4.6, 3.6, 1. , 0.2]), array([5.1, 3.3, 1.7, 0.5]), array([4.8, 3.4, 1.9, 0.2]), array([5. , 3. , 1.6, 0.2]), array([5. , 3.4, 1.6, 0.4]), array([5.2, 3.5, 1.5, 0.2]), array([5.2, 3.4, 1.4, 0.2]), array([4.7, 3.2, 1.6, 0.2]), array([4.8, 3.1, 1.6, 0.2]), array([5.4, 3.4, 1.5, 0.4]), array([5.2, 4.1, 1.5, 0.1]), array([5.5, 4.2, 1.4, 0.2]), array([4.9, 3

In [ ]:
# getting the data from the load_iris in much suitable manner
from sklearn.datasets import load_iris
iris_data = load_iris()
import pandas as pd

In [ ]:
type(iris_data)

sklearn.utils._bunch.Bunch

In [ ]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
import numpy as np

In [ ]:
iris_data_df = pd.DataFrame(np.c_[iris_data['data'], iris_data['target']], columns=iris_data['feature_names']+['className'])

In [ ]:
iris_data_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     className  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  
..         ...  
145        2.0  
146        2.0  
147        2.0  
148        2.0  
149        2.0  

[150 rows x 5 columns]

In [ ]:
# applying transformation
iris_data_df['className'] = iris_data_df['className'].apply(lambda x: iris_data['target'][int(x)])

In [ ]:
iris_data_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     className  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
145          0  
146          0  
147          0  
148          0  
149          0  

[150 rows x 5 columns]

Avoiding the transformation

In [ ]:
iris_data_sp

rdd_delta0 ParallelCollectionRDD[24] at readRDDFromFile at PythonRDD.scala:287

In [ ]:
iris_data_sp.collect()

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.

In [ ]:
def splitter(x):
  ''' sample function to do the splitting'''
  return x[0], x[1], x[2], x[3]

In [ ]:
# dataspilitting
iris_data_sp_splitted = iris_data_sp.map(splitter)
iris_data_sp_splitted.take(2)

[(5.1, 3.5, 1.4, 0.2), (4.9, 3.0, 1.4, 0.2)]

In [ ]:
iris_data_sp_splitted.take(30)

In [ ]:
for item in iris_data_sp_splitted.take(10):
  print(item)

(5.1, 3.5, 1.4, 0.2)
(4.9, 3.0, 1.4, 0.2)
(4.7, 3.2, 1.3, 0.2)
(4.6, 3.1, 1.5, 0.2)
(5.0, 3.6, 1.4, 0.2)
(5.4, 3.9, 1.7, 0.4)
(4.6, 3.4, 1.4, 0.3)
(5.0, 3.4, 1.5, 0.2)
(4.4, 2.9, 1.4, 0.2)
(4.9, 3.1, 1.5, 0.1)


Using flatMap with RDD in pyspark