In [1]:
# staking the numpy arrays in python
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(45,55)
c = [a,b] # each item will be individual numpy array object

In [3]:
c

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54])]

In [5]:
# creating horizondal stack
c = np.hstack([a,b])
print(c)

[ 0  1  2  3  4  5  6  7  8  9 45 46 47 48 49 50 51 52 53 54]


In [7]:
np.ravel([a,b])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

In [8]:
np.ravel([a,b], order='F') # column order in the two arrays ie the first one will be first column in a and second one
# will be the first element in b

array([ 0, 45,  1, 46,  2, 47,  3, 48,  4, 49,  5, 50,  6, 51,  7, 52,  8,
       53,  9, 54])

In [9]:
# creating column stack
a = np.arange(5)
b = np.arange(5,10)
c = np.arange(10,15)

In [10]:
d = np.column_stack([a,b,c])

In [11]:
d

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [15]:
np.ravel([a,b,c], order = 'F').reshape(5,3)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
import pandas as pd

In [25]:
t = pd.DataFrame(d, columns=["A","B","C"])

In [29]:

t

A  B   C
0  0  5  10
1  1  6  11
2  2  7  12
3  3  8  13
4  4  9  14

In [27]:
for i, j in t.items():
    print(i,"  ",j)

A    0    0
1    1
2    2
3    3
4    4
Name: A, dtype: int32
B    0    5
1    6
2    7
3    8
4    9
Name: B, dtype: int32
C    0    10
1    11
2    12
3    13
4    14
Name: C, dtype: int32
